SELECT 
    l.NOMBRE AS "Libro",
    l.EDITORIAL AS "Editorial",
    l.PRECIO_UNITARIO AS "Precio Unitario"
FROM LIBROS l
JOIN GENEROS_LIBROS g 
    ON l.ID_GENERO = g.ID_GENERO
WHERE g.GENERO = 'Terror'
AND l.PRECIO_UNITARIO > ALL (
    SELECT l2.PRECIO_UNITARIO
    FROM LIBROS l2
    JOIN GENEROS_LIBROS g2 
        ON l2.ID_GENERO = g2.ID_GENERO
    WHERE g2.GENERO = 'Aventura'
);
